#file config
version: 2.1

orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.2.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: gegulusgray/npx-react-demo
      DOCKER_TAG: v1.0
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USER
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          ## Please add $SSH_KEY_FINGERPRINT, $DEPLOYED_USER@ and DEPLOYED_SERVER to project's environment sooner
          fingerprints:
            - "2e:20:ce:c2:97:3d:34:26:87:64:c0:ee:5c:e2:4d:79"
      - run:  ssh -oStrictHostKeyChecking=no -v circleci@157.245.203.225 "./pull-and-deploy.sh"


workflows:
  build-test-deploy:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build-and-push
